tweak warning message about un-routable exclude routes
Signed-off-by: Daniel Lenski <dlenski@gmail.com>

diff --git a/vpnc-script b/vpnc-script
--- a/vpnc-script
+++ b/vpnc-script
@@ -318,7 +318,7 @@ if [ -n "$IPROUTE" ]; then
 		NETMASKLEN="$3"
 		ARGS=`$IPROUTE route get "$NETWORK" 2>/dev/null | fix_ip_get_output "/$NETMASKLEN"`
 		if [ -z "$ARGS" ]; then
-			echo "ignoring non-forwardable exclude route $NETWORK/$NETMASKLEN" >&2
+			echo "cannot find route for exclude route $NETWORK/$NETMASKLEN, ignoring" >&2
 			return
 		fi
 		$IPROUTE route add $ARGS
@@ -378,7 +378,7 @@ if [ -n "$IPROUTE" ]; then
 		NETMASKLEN="$2"
 		ARGS=`$IPROUTE route get "$NETWORK" 2>/dev/null | fix_ip_get_output "/$NETMASKLEN"`
 		if [ -z "$ARGS" ]; then
-			echo "ignoring non-forwardable exclude route $NETWORK/$NETMASKLEN" >&2
+			echo "cannot find route for exclude route $NETWORK/$NETMASKLEN, ignoring" >&2
 			return
 		fi
 		$IPROUTE -6 route add $ARGS
@@ -469,7 +469,7 @@ else # use route command
 		NETMASKLEN="$3"
 		DEFAULTGW="${DEFAULTGW:-`get_default_gw`}"
 		if [ -z "$DEFAULTGW" ]; then
-			echo "ignoring non-forwardable exclude route $NETWORK/$NETMASKLEN" >&2
+			echo "cannot find route for exclude route $NETWORK/$NETMASKLEN, ignoring" >&2
 			return
 		fi
 		# Add explicit route to keep traffic for this target separate
@@ -547,7 +547,7 @@ else # use route command
 		NETMASK="$2"
 		IPV6DEFAULTGW="${IPV6DEFAULTGW:-`get_ipv6_default_gw`}"
 		if [ -z "$IPV6DEFAULTGW" ]; then
-			echo "ignoring non-forwardable exclude route $NETWORK/$NETMASKLEN" >&2
+			echo "cannot find route for exclude route $NETWORK/$NETMASKLEN, ignoring" >&2
 			return
 		fi
 		# Add explicit route to keep traffic for this target separate
